### ISSUE TITLE
TextCnn运行时报错

### ISSUE THREAD

**Issue by nobody2231** [mzc421/pytorch-nlp#12]
Traceback (most recent call last):
  File "D:/spider/pytorch-nlp-master/01-TextCNN 文本分类/main.py", line 27, in <module>
    logger_init(log_level=logging.INFO)
  File "D:\spider\pytorch-nlp-master\01-TextCNN 文本分类\log.py", line 21, in logger_init
    logging.basicConfig(level=log_level,
  File "D:\Anaconda\envs\Pytorch\lib\logging\__init__.py", line 2009, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): encoding

**Comment by mzc421** [comment]
编码问题


| |
李川
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年4月10日 17:15 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [mzc421/pytorch-nlp] TextCnn运行时报错 (Issue #12) |

Traceback (most recent call last):
File "D:/spider/pytorch-nlp-master/01-TextCNN 文本分类/main.py", line 27, in
logger_init(log_level=logging.INFO)
File "D:\spider\pytorch-nlp-master\01-TextCNN 文本分类\log.py", line 21, in logger_init
logging.basicConfig(level=log_level,
File "D:\Anaconda\envs\Pytorch\lib\logging_init_.py", line 2009, in basicConfig
raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): encoding
